### PR TITLE
Enforce Line length to 100

### PR DESCRIPTION
**Pull request by harshil21**
A line length of 120 is too much imo. 100 is the standard used by most projects.

No functional change. Merge after #72

### CODE REVIEW

**Comment by JacksonElia** [comment]
NO

**Comment by harshil21** [comment]
why

**Comment by wlsanderson** [comment]
But why tho
Is it just to make code cleaner to read?

**Comment by harshil21** [comment]
yeah and you don't have to scroll horizontally as often

**Comment by wlsanderson** [comment]
at Google they enforce 80. I say we one-up them and go to 70

**Review by JacksonElia — APPROVED** [review]
fine

**Pull request merged**
